@startuml
/'
To run this diagram, you can use the following URL:
http://www.plantuml.com/plantuml/uml/

In VS Code, you can use the PlantUML extension to preview the diagram.
https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml
Be sure to set your settings to use the plantuml server to render and add the main uml server link

class diagram guidelines:
https://plantuml.com/class-diagram
'/

package "Database" {
  
  entity "User" {
    + id: int
    + name: string
    + email: string
    + wallet_address: string
    + timestamp: datetime
    + activated: boolean
    - password: string
    --
    + register(): void
    + login(email: string, password: string): boolean
    + updateProfile(username: string, email: string, password: string): void
    + linkWallet(wallet_address: string): void
    + getKYCStatus(): boolean
  }
  
  entity "Property" {
    + id: int
    + address: string
    + description: string
    + images: string
    --
    + addProperty(address: string, description: string, images: string): void
    + editProperty(id: int, address: string, description: string, images: string): void
    + deleteProperty(id: int): void
  }
  
  entity "Token" {
    + property_id: uuid
    + customization_proposed: boolean
    + customization_approved: boolean
    + price: float
    - token_amount: integer
    --
    + tokenizeProperty(property_id: int, owner_id: int): void
    + customizeToken(token_id: int, customization_data: object): void
    + approveCustomization(token_id: int): void
    + transferOwnership(token_id: int, new_owner_id: int): void
    + setPrice(token_id: int, price: float): void
    + getPrice(): void
    + transfer_tokens(): void
    + burn_tokens(): void
    + mint_fungible_tokens(): void
    + get_token_supply(): void
    + get_token_owner(): void
    + get_token_transactions(): void
    + get_token_holders(): void
    + get_token_issuers(): void
  }
  
  entity "Transaction" {
    + id: int
    + token_id: int
    + buyer_id: int
    + seller_id: int
    + amount: float
    + payment_method: string
    + timestamp: datetime
    --
    + initiateTransaction(token_id: int, buyer_id: int, seller_id: int, amount: float, payment_method: string): void
    + verifyTransaction(transaction_id: int): void
  }
  
  entity "KYC" {
    + id: int
    + user_id: int
    + document_type: string
    + document_image: string
    + verified: boolean
    --
    + submitKYCDocuments(user_id: int, document_type: string, document_image: string): void
    + verifyKYC(user_id: int): void
  }
  
  entity "Marketplace" {
    + id: int
    + token_id: int
    + price: float
    + status: string
    + listed_date: datetime
    + expiration_date: datetime
    --
    + listToken(token_id: int, price: float, expiration_date: datetime): void
    + updateTokenPrice(token_id: int, new_price: float): void
    + removeTokenListing(token_id: int): void
  }
  
  entity "Activate Token" {
    + token: string
    + user: string
    + activatedAt: datetime
    + createdAt: datetime
    + updatedAt: datetime
    --
    + activateToken(token: string, user: string): void
    + verifyActivation(token: string, user: string): void
  }

  entity "MetaMaskWallet" {
     + name: string
     - wallet_address: string
     - transaction_history: List<Transaction>
     - token_amt: integer
     - activity_log: List<activity>
     --
     + add_transaction(Transaction): void
     + add_token(token): void
     + update_account_preferences(): void
     + get_balance(token_amt): double
  }
  
  User --> Token : owns
  User --> MetaMaskWallet : has
  MetaMaskWallet --> Token : has
  Property --> Token : represents
  User --> KYC : has
  KYC --> User : verified
  User --> Transaction : initiates
  Token --> Marketplace : listed_in
  Token --> Transaction : traded_in
  "Activate Token"--> Token : activates
  "Activate Token" --> User : belongs_to
  User --> "Activate Token" : has

}
@enduml